#!/bin/bash
#
# chkconfig: 235 99 01
# description: LConf Slave Sync
### BEGIN INIT INFO
# Provides:          LConfSlaveSync
# Required-Start:    icinga
# Required-Stop:     icinga
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 5
# Default-Stop:      0 1 6
# Short-Description: start and stop LConf Slave Sync
# Description:       LConf Slave Sync
### END INIT INFO
 
sudo -u icinga /usr/local/LConf/LConfSlaveSync.pl $1
