#!/bin/bash

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root."
	exit 1
fi

DB=1
USER=ldap
GROUP=ldap
SCHEMA_CONFIG="/etc/openldap/schema"

service slapd stop
cp src/netways.schema $SCHEMA_CONFIG/
chown -R $USER:$GROUP $SCHEMA_CONFIG/*.schema
service slapd start
