#!/bin/bash

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root."
	exit 1
fi

DB=1
USER=ldap
GROUP=ldap
SCHEMA_CONFIG="/etc/openldap/slapd.d/cn=config/cn=schema"

service slapd stop
cp "tmp/cn=config/cn=schema/cn={$DB}netways.ldif" "$SCHEMA_CONFIG/cn={$DB}netways.ldif"
chown -R $USER:$GROUP $SCHEMA_CONFIG/*.ldif
service slapd start
